language: node_js
node_js:
  - "14.15.1"

services:
  - xvfb

script:
  - ng lint
  - ng build --prod
  - ng test --watch=false

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

before_script: npm rebuild node-sass;
